"""Gesture bank — the bird's motor score, generated by a vocal CPG.

A gesture is a smooth path (alpha(t), beta(t)) through the phonating region of
parameter space: alpha ~ air-sac pressure, beta ~ syringeal tension.

Rather than draw those paths from splines or sinusoids, we *generate* them the
way the bird does: from a low-dimensional nonlinear system of the same kind as
the syrinx itself. Alonso, Alliende, Goller & Mindlin (Phys. Rev. E 79, 041929,
2009) showed that the diversity of air-sac pressure patterns in canary song is
not a continuum but a small discrete set of shapes — the *subharmonic solutions
of a forced normal form*. Fit one syllable's pressure pattern and the others
fall out of the same model at other parameters. The mechanistic version (Alonso
et al., Front. Comput. Neurosci. 9:41, 2015; reviewed in Mindlin, Chaos 27,
2017) is a Wilson-Cowan pair of excitatory / inhibitory rate populations::

    de/dt = r_e (-e + S(rho_e + a_ee e + a_ei i + F(t)))
    di/dt = r_i (-i + S(rho_i + a_ie e + a_ii i))          S(x) = 1/(1+e^-x)

with (a_ee, a_ei, a_ie, a_ii) = (10, -10, 10, 2). The (rho_e, rho_i) plane
contains a Hopf line tangent to a saddle-node curve plus a cusp; the four
canonical canary respiratory gestures — long tonal expirations, near-harmonic,
period-2, and pulsatile — are the four regions of that plane. ``F(t)`` is the
periodic "HVC" burst clock; because the CPG sits near those bifurcations it
locks to F in n:1 subharmonics, so one continuous knob (the clock rate) yields
a staircase of *distinct but structurally related* syllable shapes.

Three consequences matter for the search:

* syllable onsets and silences are emergent — alpha crosses the phonation onset
  because of the CPG's own relaxation dynamics, not because we clipped a sine;
* the same model in its relaxation regime covers anuran pulse trains, where
  slow (<35 Hz) and fast (>50 Hz) trill CPGs are the conserved motif
  (Barkan et al., eLife 12:e86299, 2023);
* the bank is *illuminated* rather than sampled — see :func:`illuminate`.

Readout to (alpha, beta) follows the reconstructions from real song (Perl et
al., Phys. Rev. E 84, 051909, 2011; Boari et al., J. Neurophysiol. 2015):
pressure tracks the envelope, tension tracks the fundamental, and the two are
correlated but *lagged*. The sign of that lag is what makes a syllable an
up-sweep or a down-sweep.

The phonating region below was mapped empirically against
:mod:`callsong.synth` (see ``scripts/probe_phonation.py``) rather than
transcribed from a paper, because published normal forms differ in how they
absorb the signs of alpha and beta.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

# ── phonating region of the reference instrument ────────────────────────────
# Measured on the Mindlin-default genome with the formants bypassed:
#   alpha <= -0.05  is silent for every beta (the labia do not oscillate);
#   onset is at alpha ~ +0.02, moving slightly lower as beta rises (the SNILC
#   boundary);  beta drives the fundamental monotonically, 313 Hz at beta=0 to
#   6.35 kHz at beta=2.6 — matching the 413-6780 Hz zebra-finch range Boari et
#   al. cover with 0.002 < beta < 2.99.
ALPHA_MIN, ALPHA_MAX = -0.05, 0.30
ALPHA_ONSET = 0.02
BETA_MIN, BETA_MAX = 0.0, 2.6

# ── Wilson-Cowan connectivity (Mindlin, Chaos 27, 2017, Fig. 12) ────────────
A_EE, A_EI, A_IE, A_II = 10.0, -10.0, 10.0, 2.0

# The CPG lives on millisecond timescales, so it is integrated on a control
# grid and interpolated up to the audio rate.
CTRL_SR = 4_000.0

# The syllable clock only runs during the middle of the window. Outside it the
# CPG relaxes to its own fixed point — silent for most parameter sets — so the
# call gets a real onset and tail-off instead of running edge to edge. Real
# calls are bounded events, and BirdNET is trained on clips that contain the
# whole event rather than a slice through the middle of one.
PHRASE_LO, PHRASE_HI = 1.0 / 3.0, 2.0 / 3.0
# Raised-cosine edges, asymmetric like a real expiratory pulse: pressure comes
# up fast and bleeds away slower. Long enough that neither end clicks.
PHRASE_ATTACK_S, PHRASE_DECAY_S = 0.03, 0.15

# ── CPG genome: name, low, high ─────────────────────────────────────────────
# rho_e/rho_i place the pair in the plane containing the Hopf line and the
# cusp; rate_e/rate_i are the two interacting timescales (the circular model
# uses a ~7:1 ratio); f_clock/amp/duty are the HVC burst train it locks to;
# the rest is the (alpha, beta) readout.
GESTURE_SPEC: list[tuple[str, float, float]] = [
    ("rho_e",    -4.0,    4.0),   # standing drive to the excitatory population
    ("rho_i",   -11.0,   -1.0),   # ... and to the inhibitory one
    ("rate_e",   40.0,  600.0),   # 1/tau_e  (s^-1)
    ("rate_i",   10.0,  300.0),   # 1/tau_i  (s^-1)
    ("f_clock",   1.0,   60.0),   # forcing rate (Hz) — syllable clock
    ("amp",       0.0,    8.0),   # forcing amplitude (0 = autonomous CPG)
    ("duty",     0.05,    0.9),   # forcing burst width, fraction of the period
    ("lag_ms",  -20.0,   20.0),   # beta lag behind alpha; sign = sweep direction
    ("w_e",      -1.2,    1.2),   # beta <- lagged excitatory activity
    ("w_i",      -1.2,    1.2),   # beta <- inhibitory activity
    ("b_bias",   -0.3,    1.0),   # beta offset (mean tension)
    ("b_ramp",   -0.8,    0.8),   # slow tension drift across the phrase
    ("a_gain",    0.6,    1.8),   # alpha <- excitatory activity
    ("a_bias",   -0.7,   0.15),   # alpha offset (how far above/below onset)
]

G_NAMES = [s[0] for s in GESTURE_SPEC]
G_LOW = np.array([s[1] for s in GESTURE_SPEC], dtype=np.float64)
G_HIGH = np.array([s[2] for s in GESTURE_SPEC], dtype=np.float64)
N_GPARAMS = len(GESTURE_SPEC)

(P_RHO_E, P_RHO_I, P_RATE_E, P_RATE_I, P_FCLK, P_AMP, P_DUTY, P_LAG,
 P_WE, P_WI, P_BBIAS, P_BRAMP, P_AGAIN, P_ABIAS) = range(N_GPARAMS)

# ── descriptor axes for the gesture archive ─────────────────────────────────
# 1. log2 modulation rate: sustained notes (~0.5 Hz) .. insect-fast trills,
#    counting repetition in pressure (syllables) or tension (warble).
# 2. mean per-cycle tension sweep: -1 fully down-swept .. +1 fully up-swept.
RATE_LOG2_LO, RATE_LOG2_HI = -1.0, 6.5
SWEEP_LO, SWEEP_HI = -1.0, 1.0
GRID_SHAPE = (12, 5)

MIN_VOICED = 0.05     # below this the gesture is silence and is discarded
GTE_DIP = 0.25        # fraction of the pressure excursion a dip must clear to
                      # count as a syllable boundary
GTE_TAIL = 0.02       # percentile tail trimmed when measuring that excursion
QUALITY_FLOOR = 0.15  # elites below this quality are not selectable for the bank.
                      # Absolute, not relative to the best: a sustained whistle
                      # scores low (no pressure excursion) but is a call type we
                      # want in the bank, whereas a barely-phonating gesture is
                      # a wasted render at any relative threshold.


@dataclass
class GestureBank:
    """The selected gestures plus the provenance needed to plot / re-derive."""

    paths: np.ndarray        # (n_gestures, 2, n_samples) float32 — alpha, beta
    params: np.ndarray       # (n_gestures, N_GPARAMS) CPG parameters
    descriptors: np.ndarray  # (n_gestures, 2) (log2 modulation rate, tension sweep)
    quality: np.ndarray      # (n_gestures,)
    coverage: float          # fraction of archive cells the sweep filled

    def save(self, path: str) -> None:
        np.savez_compressed(
            path, paths=self.paths, params=self.params,
            descriptors=self.descriptors, quality=self.quality,
            coverage=self.coverage, names=np.array(G_NAMES),
        )


def _sigmoid(x: np.ndarray) -> np.ndarray:
    return 1.0 / (1.0 + np.exp(-np.clip(x, -60.0, 60.0)))


def _phrase_gate(t: float, duration: float) -> float:
    """The expiratory pressure pulse: one bounded phrase in the middle of the
    window, zero outside it."""
    t0, t1 = PHRASE_LO * duration, PHRASE_HI * duration
    atk = min(PHRASE_ATTACK_S, 0.4 * (t1 - t0))
    dec = min(PHRASE_DECAY_S, 0.4 * (t1 - t0))
    if t <= t0 or t >= t1:
        return 0.0
    if t < t0 + atk:
        return 0.5 * (1.0 - math.cos(math.pi * (t - t0) / atk))
    if t > t1 - dec:
        return 0.5 * (1.0 - math.cos(math.pi * (t1 - t) / dec))
    return 1.0


def _phrase_envelope(n_steps: int) -> np.ndarray:
    """:func:`_phrase_gate` sampled over the control grid."""
    duration = n_steps / CTRL_SR
    return np.array([_phrase_gate(k / CTRL_SR, duration)
                     for k in range(n_steps)])


def _forcing(t: float, f_clock: np.ndarray, amp: np.ndarray,
             duty: np.ndarray, duration: float) -> np.ndarray:
    """Periodic raised-cosine burst train — the HVC syllable clock — gated to
    the middle of the window by :func:`_phrase_gate`."""
    gate = _phrase_gate(t, duration)
    if gate == 0.0:
        return np.zeros_like(amp)
    phase = (t * f_clock) % 1.0
    inside = phase < duty
    u = np.where(inside, phase / duty, 0.0)
    return np.where(inside,
                    gate * amp * 0.5 * (1.0 - np.cos(2.0 * np.pi * u)), 0.0)


def integrate(params: np.ndarray, n_steps: int) -> tuple[np.ndarray, np.ndarray]:
    """RK4-integrate the forced Wilson-Cowan pair for a batch of parameters.

    ``params`` is (N, N_GPARAMS) in physical units. Returns (e, i), each
    (N, n_steps) at :data:`CTRL_SR`, started from rest (silence).
    """
    rho_e, rho_i = params[:, P_RHO_E], params[:, P_RHO_I]
    rate_e, rate_i = params[:, P_RATE_E], params[:, P_RATE_I]
    f_clk, amp, duty = params[:, P_FCLK], params[:, P_AMP], params[:, P_DUTY]

    dt = 1.0 / CTRL_SR
    duration = n_steps / CTRL_SR
    n = len(params)
    e = np.zeros(n)
    i = np.zeros(n)
    out_e = np.empty((n, n_steps), dtype=np.float32)
    out_i = np.empty((n, n_steps), dtype=np.float32)

    def rhs(ev, iv, force):
        de = rate_e * (-ev + _sigmoid(rho_e + A_EE * ev + A_EI * iv + force))
        di = rate_i * (-iv + _sigmoid(rho_i + A_IE * ev + A_II * iv))
        return de, di

    f0 = _forcing(0.0, f_clk, amp, duty, duration)
    for k in range(n_steps):
        out_e[:, k] = e
        out_i[:, k] = i
        t = k * dt
        f1 = _forcing(t + 0.5 * dt, f_clk, amp, duty, duration)
        f2 = _forcing(t + dt, f_clk, amp, duty, duration)
        k1e, k1i = rhs(e, i, f0)
        k2e, k2i = rhs(e + 0.5 * dt * k1e, i + 0.5 * dt * k1i, f1)
        k3e, k3i = rhs(e + 0.5 * dt * k2e, i + 0.5 * dt * k2i, f1)
        k4e, k4i = rhs(e + dt * k3e, i + dt * k3i, f2)
        e = e + dt / 6.0 * (k1e + 2 * k2e + 2 * k3e + k4e)
        i = i + dt / 6.0 * (k1i + 2 * k2i + 2 * k3i + k4i)
        f0 = f2                      # this step's endpoint is the next start

    return out_e, out_i


def readout(e: np.ndarray, i: np.ndarray,
            params: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Map CPG activity to (alpha, beta) at the control rate.

    Pressure follows the excitatory population directly; tension follows a
    *lagged* copy of it mixed with the inhibitory population plus a slow drift,
    which is what produces correlated-but-not-identical envelope / pitch
    contours and, via the sign of the lag, up- vs down-swept syllables.
    """
    n, k = e.shape
    shift = np.rint(params[:, P_LAG] * 1e-3 * CTRL_SR).astype(int)

    e_lag = np.empty_like(e)
    for row, s in enumerate(shift):
        if s > 0:                       # beta trails alpha
            s = min(s, k - 1)
            e_lag[row, :s] = e[row, 0]
            e_lag[row, s:] = e[row, :k - s]
        elif s < 0:                     # beta leads alpha
            s = min(-s, k - 1)
            e_lag[row, :k - s] = e[row, s:]
            e_lag[row, k - s:] = e[row, -1]
        else:
            e_lag[row] = e[row]

    ramp = np.linspace(0.0, 1.0, k, dtype=np.float32)[None, :]

    # Pressure is gated by the phrase envelope, not just the syllable clock:
    # with rho_e in the oscillatory wedge a good share of these CPGs free-run,
    # so gating only the forcing would leave them sounding edge to edge. The
    # envelope IS the expiratory pulse, and pressure is what it drives.
    env = _phrase_envelope(k)[None, :]
    a_unit = env * np.clip(
        params[:, P_ABIAS, None] + params[:, P_AGAIN, None] * e, 0.0, 1.0)

    # Tension is gated by the same envelope. beta multiplies x in the source,
    # so a beta left warbling through the silence is *parametric* forcing: it
    # pumps the oscillator into sounding below the pressure threshold, which is
    # how phonation leaked into the first third even with alpha held down.
    b_unit = env * np.clip(params[:, P_BBIAS, None]
                           + params[:, P_WE, None] * e_lag
                           + params[:, P_WI, None] * i
                           + params[:, P_BRAMP, None] * ramp, 0.0, 1.0)

    alpha = ALPHA_MIN + (ALPHA_MAX - ALPHA_MIN) * a_unit
    beta = BETA_MIN + (BETA_MAX - BETA_MIN) * b_unit
    return alpha.astype(np.float32), beta.astype(np.float32)


def _gate_rate(x: np.ndarray, gate: np.ndarray, duration: np.ndarray | float,
               floor: float | None = None) -> tuple[np.ndarray, np.ndarray]:
    """Rate at which ``x`` rises past a GTE threshold, counted only where
    ``gate`` holds. The threshold sits :data:`GTE_DIP` of the way up the
    channel's own excursion *within the gate*, so it adapts to gestures that
    modulate over a narrow band, and is floored at ``floor`` when given.

    The excursion is measured by :data:`GTE_TAIL` percentiles rather than
    min/max: the CPG starts from rest, and that one-off startup swing is often
    wider than the whole steady-state modulation it then settles into, which
    would push the threshold clear of every subsequent cycle."""
    has_gate = gate.any(axis=1)
    xg = np.where(gate, x, np.nan)
    xg[~has_gate] = 0.0                  # keep all-NaN rows out of the reduction
    lo = np.nanpercentile(xg, 100.0 * GTE_TAIL, axis=1)
    hi = np.nanpercentile(xg, 100.0 * (1.0 - GTE_TAIL), axis=1)
    thresh = lo + GTE_DIP * (hi - lo)
    if floor is not None:
        thresh = np.maximum(thresh, floor)
    thresh = np.where(has_gate, thresh, np.inf)[:, None]

    active = (x > thresh) & gate
    n = (active[:, 1:] & ~active[:, :-1]).sum(axis=1) + active[:, 0]
    return n / duration, active


def describe(alpha: np.ndarray, beta: np.ndarray,
             duration: float) -> tuple[np.ndarray, np.ndarray]:
    """Behaviour descriptors and probe quality for a batch of gestures.

    Descriptors are (log2 modulation rate, mean per-cycle tension sweep).
    Quality asks how good a *probe* the gesture is: how much of the phonating
    region it sweeps the instrument through, weighted by how much of the
    gesture actually makes sound.
    """
    voiced = alpha > ALPHA_ONSET
    v_frac = voiced.mean(axis=1)

    # Rates are per second *of call*, not per second of window: the syllable
    # clock only runs during the middle third, so dividing by the window length
    # would report every gesture as three times slower than it sounds.
    k_steps = alpha.shape[1]
    idx = np.arange(k_steps)
    first = np.where(voiced, idx, k_steps).min(axis=1)
    last = np.where(voiced, idx, -1).max(axis=1)
    span = np.maximum((last - first + 1) / k_steps * duration, 0.2)

    # Repetition rate of the motor score. Pressure syllables are delimited by
    # *significant minima*, not only by silences — a trill that dips without
    # ever crossing the phonation onset is still a trill. That is the GTE
    # segmentation rule of Boari et al. / Amador et al. (a minimum counts when
    # it is meaningfully below the surrounding maxima), reduced to one
    # threshold per gesture so it vectorises. The same rule on the tension
    # channel catches warbles the bird sings at constant pressure — pure
    # frequency modulation, which is a trill to the ear but a single syllable
    # to the respiratory system. The gesture's rate is whichever is faster.
    rate_a, active = _gate_rate(alpha, voiced, span, floor=ALPHA_ONSET)
    rate_b, _ = _gate_rate(beta, voiced, span)
    rate = np.maximum(rate_a, rate_b)
    n_cycles = np.maximum(rate * span, 1.0)
    d_rate = np.clip(np.log2(np.maximum(rate, 2.0 ** RATE_LOG2_LO)),
                     RATE_LOG2_LO, RATE_LOG2_HI)

    # Net tension travel accumulated over syllable *bodies*, per modulation
    # cycle: a repeated up-sweep accumulates +delta each cycle, a down-sweep
    # -delta, a symmetric warble cancels to ~0. Measured over `active` rather
    # than `voiced` so the tension resetting during the inter-syllable dip does
    # not cancel the sweep it is resetting from.
    d_beta = np.diff(beta, axis=1, prepend=beta[:, :1])
    travel = (d_beta * active).sum(axis=1)
    d_sweep = np.clip(travel / (n_cycles * (BETA_MAX - BETA_MIN)),
                      SWEEP_LO, SWEEP_HI)

    # Spread of each control parameter over the phonating part of the gesture.
    n_v = np.maximum(voiced.sum(axis=1), 1)

    def voiced_std(x):
        mu = (x * voiced).sum(axis=1) / n_v
        var = ((x - mu[:, None]) ** 2 * voiced).sum(axis=1) / n_v
        return np.sqrt(np.maximum(var, 0.0))

    a_span = np.clip(2.0 * voiced_std(alpha) / (ALPHA_MAX - ALPHA_ONSET), 0, 1)
    b_span = np.clip(2.0 * voiced_std(beta) / (BETA_MAX - BETA_MIN), 0, 1)

    # Voicing is scored against the phrase window, not the whole clip: the
    # pressure pulse only occupies PHRASE_LO..PHRASE_HI, so a gesture that
    # phonates throughout its phrase tops out near that fraction and should not
    # be marked down for the silence either side of it.
    v_ref = 0.5 * (PHRASE_HI - PHRASE_LO)
    quality = ((0.2 + 0.8 * a_span) * (0.2 + 0.8 * b_span)
               * np.minimum(v_frac / v_ref, 1.0))
    quality = np.where(v_frac < MIN_VOICED, 0.0, quality)

    return np.stack([d_rate, d_sweep], axis=1), quality


def _cell(descriptors: np.ndarray) -> np.ndarray:
    """Descriptor rows -> (row, col) archive cell indices."""
    lo = np.array([RATE_LOG2_LO, SWEEP_LO])
    hi = np.array([RATE_LOG2_HI, SWEEP_HI])
    u = (descriptors - lo) / (hi - lo)
    idx = np.floor(u * np.array(GRID_SHAPE)).astype(int)
    return np.clip(idx, 0, np.array(GRID_SHAPE) - 1)


def _farthest_point(descriptors: np.ndarray, quality: np.ndarray,
                    n: int) -> list[int]:
    """Greedy max-min selection in normalised descriptor space, seeded by the
    highest-quality elite — spread the bank out rather than clustering it."""
    lo = np.array([RATE_LOG2_LO, SWEEP_LO])
    hi = np.array([RATE_LOG2_HI, SWEEP_HI])
    u = (descriptors - lo) / (hi - lo)

    if n <= 0:
        return []
    chosen = [int(np.argmax(quality))]
    dist = np.linalg.norm(u - u[chosen[0]], axis=1)
    while len(chosen) < min(n, len(u)):
        nxt = int(np.argmax(dist))
        if dist[nxt] <= 0.0:                      # exhausted distinct points
            remaining = [k for k in np.argsort(quality)[::-1] if k not in chosen]
            chosen.extend(remaining[:n - len(chosen)])
            break
        chosen.append(nxt)
        dist = np.minimum(dist, np.linalg.norm(u - u[nxt], axis=1))
    return chosen


def _to_audio(x_ctrl: np.ndarray, n_samples: int, sr: float) -> np.ndarray:
    """Control-rate -> audio-rate, with the interpolation kinks smoothed off."""
    k = x_ctrl.shape[1]
    t_ctrl = np.arange(k) / CTRL_SR
    t_aud = np.arange(n_samples) / sr
    out = np.stack([np.interp(t_aud, t_ctrl, row) for row in x_ctrl])

    win = max(3, int(2 * sr / CTRL_SR) | 1)
    kern = np.hanning(win + 2)[1:-1]
    kern /= kern.sum()
    pad = win // 2
    smoothed = np.empty_like(out)
    for row in range(len(out)):
        padded = np.pad(out[row], pad, mode="edge")
        smoothed[row] = np.convolve(padded, kern, mode="valid")
    return smoothed.astype(np.float32)


def paths_from_params(params: np.ndarray, n_samples: int,
                      sr: float = 48_000.0) -> np.ndarray:
    """CPG parameters (N, N_GPARAMS) -> motor paths (N, 2, n_samples).

    The search-facing entry point: every genome carries its own gesture, so
    this runs per candidate rather than once per bank.
    """
    n_steps = max(2, int(round(n_samples / sr * CTRL_SR)))
    e, i = integrate(np.asarray(params, dtype=np.float64), n_steps)
    alpha, beta = readout(e, i, params)
    return np.stack([_to_audio(alpha, n_samples, sr),
                     _to_audio(beta, n_samples, sr)], axis=1).astype(np.float32)


def ramp_gesture(n_samples: int) -> np.ndarray:
    """The diagnostic probe: a pressure ramp across the phonation onset with
    rising tension, so one sweep traces a slice of the bifurcation diagram.

    Confined to the same phrase window as the CPG gestures — it still crosses
    the onset, and every gesture in the bank then shares one rule about when
    sound is allowed."""
    t = np.linspace(0.0, 1.0, n_samples, dtype=np.float32)
    u = np.clip((t - PHRASE_LO) / (PHRASE_HI - PHRASE_LO), 0.0, 1.0)
    inside = (t >= PHRASE_LO) & (t <= PHRASE_HI)
    alpha = np.where(inside,
                     ALPHA_MIN + (ALPHA_MAX - ALPHA_MIN) * np.clip(1.5 * u, 0, 1),
                     ALPHA_MIN)
    beta = BETA_MIN + (BETA_MAX - BETA_MIN) * u
    return np.stack([alpha, beta]).astype(np.float32)


def illuminate(seed: int, n_gestures: int, n_samples: int, sr: float = 48_000.0,
               n_candidates: int = 2_000, include_ramp: bool = True,
               chunk: int = 1_024) -> GestureBank:
    """Illuminate the CPG parameter space, then pick a spread-out bank from it.

    Rather than seed an RNG and hope, we sweep ``n_candidates`` CPG parameter
    sets, drop each into a (modulation rate x tension sweep) archive keeping the
    best probe per cell, and select ``n_gestures`` elites by farthest-point
    sampling. The bank is therefore diverse *by construction* and, being driven
    from ``seed``, identical for every instrument and across runs.
    """
    rng = np.random.default_rng(seed)
    duration = n_samples / sr
    n_steps = max(2, int(round(duration * CTRL_SR)))

    params = G_LOW + rng.random((n_candidates, N_GPARAMS)) * (G_HIGH - G_LOW)

    descriptors = np.empty((n_candidates, 2))
    quality = np.empty(n_candidates)
    for start in range(0, n_candidates, chunk):
        sl = slice(start, start + chunk)
        e, i = integrate(params[sl], n_steps)
        alpha, beta = readout(e, i, params[sl])
        descriptors[sl], quality[sl] = describe(alpha, beta, duration)

    # ── archive: best probe per (rate, sweep) cell ───────────────────────────
    best = {}
    for k in np.argsort(quality):          # ascending, so the best wins the cell
        if quality[k] <= 0.0:
            continue
        best[tuple(_cell(descriptors[k:k + 1])[0])] = k
    elites = np.array(sorted(best.values()), dtype=int)
    coverage = len(best) / float(GRID_SHAPE[0] * GRID_SHAPE[1])

    if len(elites) == 0:
        raise RuntimeError(
            "gesture sweep produced no phonating candidates — check that "
            "ALPHA_ONSET still matches callsong.synth")

    # Spread the bank out, but not into cells whose best probe is degenerate
    # (barely phonating, or sitting on the onset with no excursion).
    pool = elites[quality[elites] >= QUALITY_FLOOR]
    if len(pool) == 0:
        pool = elites
    n_cpg = n_gestures - 1 if include_ramp else n_gestures
    picked = pool[_farthest_point(descriptors[pool], quality[pool], n_cpg)]

    # Re-integrate just the winners and lift them to the audio rate.
    e, i = integrate(params[picked], n_steps)
    alpha, beta = readout(e, i, params[picked])
    paths = np.stack([_to_audio(alpha, n_samples, sr),
                      _to_audio(beta, n_samples, sr)], axis=1)

    if include_ramp:
        paths = np.concatenate([ramp_gesture(n_samples)[None], paths], axis=0)
        params = np.concatenate([np.full((1, N_GPARAMS), np.nan), params[picked]])
        descs = np.concatenate([np.full((1, 2), np.nan), descriptors[picked]])
        quals = np.concatenate([[np.nan], quality[picked]])
    else:
        params, descs, quals = params[picked], descriptors[picked], quality[picked]

    return GestureBank(paths=paths.astype(np.float32), params=params,
                       descriptors=descs, quality=quals, coverage=coverage)


def make_gesture_bank(seed: int, n_gestures: int, n_samples: int,
                      sr: float = 48_000.0, n_candidates: int = 2_000,
                      include_ramp: bool = True) -> np.ndarray:
    """Fixed bank of gestures, shape (n_gestures, 2, n_samples).

    Channel 0 = alpha(t) (air-sac pressure), channel 1 = beta(t) (syringeal
    tension), at the audio rate. Thin wrapper over :func:`illuminate` for
    callers that only want the paths.
    """
    return illuminate(seed, n_gestures, n_samples, sr, n_candidates,
                      include_ramp).paths
